version: '3.1'

services:

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prueba
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306

# docker exec -it -u root confluent_kafka-3_1 connect-standalone \
#/compartida/connect.properties /compartida/fichero-entradas.properties
# Además tendria que tener el contenedor acceso a  : 